# backend/plan_parser.py

"""
Parses AI-generated markdown text into a structured `CompletePlan` object.

This module is responsible for taking the free-form markdown output from the
AI agent and converting it into a predictable, structured format that the rest
of the application can work with.
"""

import re
from backend.local_agents.writer import CompletePlan, DailyPlan, Task
from backend.schemas import TrainingMaterial, TrainingResource

def parse_markdown_to_plan(markdown_text: str) -> CompletePlan:
    """
    Parses a markdown string to extract daily plans and tasks.

    This function iterates through each line of the markdown text, using regular
    expressions to identify and extract day headers and task list items. It
    constructs a `CompletePlan` object containing a list of `DailyPlan` objects.

    Args:
        markdown_text: The raw markdown string generated by the AI agent.

    Returns:
        A `CompletePlan` object representing the structured study plan.
    
    Raises:
        ValueError: If the markdown format is unexpected and parsing fails.
    """
    daily_plans: list[DailyPlan] = []
    current_day = 0
    current_tasks: list[Task] = []
    
    # This regex is designed to be flexible and capture tasks in the format:
    # "- 60 mins: **Task Name** - Task description..."
    # It accounts for variations in spacing and the word "min" vs "mins".
    # Groups: 1=duration, 2=name, 3=description
    task_pattern = re.compile(r'-\s*(\d+)\s*mins?:\s*\*\*(.*?)\*\*\s*-\s*(.*)')
    
    lines = markdown_text.split('\n')
    for line in lines:
        line = line.strip()
        
        # Detect a day header (e.g., "# Day 1", "## Day 2").
        day_match = re.search(r'^#+\s*Day\s+(\d+)', line, re.IGNORECASE)
        if day_match:
            # When we find a new day, save the previous day's tasks.
            if current_day > 0 and current_tasks:
                daily_plans.append(DailyPlan(day=current_day, tasks=current_tasks))
            
            # Start a new list for the new day.
            current_day = int(day_match.group(1))
            current_tasks = []
            continue

        # Detect a task list item.
        task_match = task_pattern.match(line)
        if task_match:
            try:
                duration = int(task_match.group(1))
                name = task_match.group(2).strip()
                description = task_match.group(3).strip()
                current_tasks.append(Task(duration=duration, name=name, description=description))
            except (IndexError, ValueError):
                # This can happen if the regex matches but the groups are not as expected.
                # In a production app, you might want to log this error.
                print(f"Warning: Could not parse malformed task line: {line}")


    # After the loop, append the last day's tasks if they exist.
    if current_day > 0 and current_tasks:
        daily_plans.append(DailyPlan(day=current_day, tasks=current_tasks))

    if not daily_plans:
        raise ValueError("Could not find any valid days or tasks in the provided markdown plan.")

    # The AI doesn't generate a summary, so we provide a default one.
    summary = "Your personalized interview preparation quest."
    return CompletePlan(short_summary=summary, daily_plans=daily_plans)


def parse_markdown_to_training_material(markdown_text: str) -> TrainingMaterial:
    """
    Parses a markdown string to extract training material.

    This function iterates through each line of the markdown text, using regular
    expressions to identify and extract the explanation and resources.

    Args:
        markdown_text: The raw markdown string generated by the AI agent.

    Returns:
        A `TrainingMaterial` object representing the structured training material.

    Raises:
        ValueError: If the markdown format is unexpected and parsing fails.
    """
    explanation = ""
    resources: list[TrainingResource] = []
    
    # This regex is designed to be flexible and capture resources in the format:
    # "- [https://...](https://...) (10 mins)"
    # Groups: 1=url, 2=duration
    resource_pattern = re.compile(r'-\s*\[(https?://.*?)\]\(https?://.*?\)\s*\((\d+)\s*mins?\)')
    
    lines = markdown_text.split('\n')
    in_explanation = False
    in_resources = False
    
    for line in lines:
        line = line.strip()
        
        if line.lower() == "# explanation":
            in_explanation = True
            in_resources = False
            continue
        elif line.lower() == "# resources":
            in_explanation = False
            in_resources = True
            continue
            
        if in_explanation:
            explanation += line + "\n"
        elif in_resources:
            resource_match = resource_pattern.match(line)
            if resource_match:
                try:
                    url = resource_match.group(1).strip()
                    duration = int(resource_match.group(2))
                    resources.append(TrainingResource(url=url, estimated_reading_time_minutes=duration))
                except (IndexError, ValueError):
                    print(f"Warning: Could not parse malformed resource line: {line}")

    if not explanation or not resources:
        raise ValueError("Could not find a valid explanation or resources in the provided markdown.")
        
    return TrainingMaterial(explanation=explanation.strip(), resources=resources)
